# All the variables should be queried from .env file.
log_level: "DEBUG"
spotify:
  client_id: !ENV ${CLIENT_ID}
  client_secret: !ENV ${CLIENT_SECRET}
database:
  database: !ENV ${MYSQL_DATABASE}
  host: !ENV ${MYSQL_HOST}
  user: !ENV ${MYSQL_USER}
  password: !ENV ${MYSQL_PASSWORD}