version: "3.3"
services:
  web:
    # Build from local.
    # build: .
    # Build from remote GitHub branch.
    image: ghcr.io/lunarmint/spotipyn/spotipyn:latest
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 -w 3 spotipyn:spotipyn
    ports:
        - "8080:5000"
    volumes:
        - ${CONFIG}:/app/config.yml
        - ${LOGS_FOLDER}:/app/logs/
    environment:
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
        - SECRET_KEY=${SECRET_KEY}
        - MYSQL_HOST=db
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=spotipyn
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
        - ${DATABASE_FOLDER}:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: spotipyn
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
